version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    container_name: app-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - backend-data:/usr/src/app/data
      - backend-logs:/usr/src/app/logs
      - backend-uploads:/usr/src/app/uploads
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: app-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:4000
    volumes:
      - frontend-dist:/app/dist
      - frontend-cache:/app/node_modules/.cache
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  # Backend volumes for data persistence
  backend-data:
    driver: local
  backend-logs:
    driver: local
  backend-uploads:
    driver: local
  
  # Frontend volumes for build artifacts and cache
  frontend-dist:
    driver: local
  frontend-cache:
    driver: local
