apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      namespace: uber
      labels: 
        app: mongodb
    spec:
      containers:
      - name: uber-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
        - name: DB_CONNECT
          value: "mongodb://localhost:27017/uber"
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongodb-pvc